	$(document).ready(function () {
	$('.aprilissue').click(function () {
	$('#viewbox').html('<h1><a href="/tribunemagazine"><span class="glyphicon glyphicon-arrow-left"></span></a></h1><br><div class="row"><div class="col-md-2"></div><div class="col-md-8"><center><div id="carousel-example-generic"class="carousel slide"data-interval="false"><!--Wrapper for slides--><div class="carousel-inner"><div class="item active"><img src="img/april/page01.jpg"alt=""></div><div class="item"><img src="img/april/page02.jpg"alt=""></div><div class="item"><img src="img/april/page03.jpg"alt=""></div><div class="item"><img src="img/april/page04.jpg"alt=""></div><div class="item"><img src="img/april/page05.jpg"alt=""></div><div class="item"><img src="img/april/page06.jpg"alt=""></div><div class="item"><img src="img/april/page07.jpg"alt=""></div><div class="item"><img src="img/april/page08.jpg"alt=""></div><div class="item"><img src="img/april/page09.jpg"alt=""></div><div class="item"><img src="img/april/page10.jpg"alt=""></div><div class="item"><img src="img/april/page11.jpg"alt=""></div><div class="item"><img src="img/april/page12.jpg"alt=""></div><div class="item"><img src="img/april/page13.jpg"alt=""></div><div class="item"><img src="img/april/page14.jpg"alt=""></div><div class="item"><img src="img/april/page15.jpg"alt=""></div><div class="item"><img src="img/april/page16.jpg"alt=""></div><div class="item"><img src="img/april/page17.jpg"alt=""></div><div class="item"><img src="img/april/page18.jpg"alt=""></div><div class="item"><img src="img/april/page19.jpg"alt=""></div><div class="item"><img src="img/april/page20.jpg"alt=""></div><div class="item"><img src="img/april/page21.jpg"alt=""></div><div class="item"><img src="img/april/page22.jpg"alt=""></div></div><!--Controls--><a class="left carousel-control"href="#carousel-example-generic"data-slide="prev"><span class="icon-prev"></span></a><a class="right carousel-control"href="#carousel-example-generic"data-slide="next"><span class="icon-next"></span></a></div></div><div class="col-md-2"></div></center>'
		);
	});
	$('.mayissue').click(function () {
	$('#viewbox').html('<h1><a href="/tribunemagazine"><span class="glyphicon glyphicon-arrow-left"></span></a></h1><br><div class="row"><div class="col-md-2"></div><div class="col-md-8"><center><div id="carousel-example-generic"class="carousel slide"data-interval="false"><!--Wrapper for slides--><div class="carousel-inner"><div class="item active"><img src="img/may/page01.jpg"alt=""></div><div class="item"><img src="img/may/page02.jpg"alt=""></div><div class="item"><img src="img/may/page03.jpg"alt=""></div><div class="item"><img src="img/may/page04.jpg"alt=""></div><div class="item"><img src="img/may/page05.jpg"alt=""></div><div class="item"><img src="img/may/page06.jpg"alt=""></div><div class="item"><img src="img/may/page07.jpg"alt=""></div><div class="item"><img src="img/may/page08.jpg"alt=""></div><div class="item"><img src="img/may/page09.jpg"alt=""></div><div class="item"><img src="img/may/page10.jpg"alt=""></div><div class="item"><img src="img/may/page11.jpg"alt=""></div><div class="item"><img src="img/may/page12.jpg"alt=""></div><div class="item"><img src="img/may/page13.jpg"alt=""></div><div class="item"><img src="img/may/page14.jpg"alt=""></div><div class="item"><img src="img/may/page15.jpg"alt=""></div><div class="item"><img src="img/may/page16.jpg"alt=""></div><div class="item"><img src="img/may/page17.jpg"alt=""></div><div class="item"><img src="img/may/page18.jpg"alt=""></div></div><!--Controls--><a class="left carousel-control"href="#carousel-example-generic"data-slide="prev"><span class="icon-prev"></span></a><a class="right carousel-control"href="#carousel-example-generic"data-slide="next"><span class="icon-next"></span></a></div></div><div class="col-md-2"></div></center>');
	});
	$('.juneissue').click(function () {
	$('#viewbox').html('<h1><a href="/tribunemagazine"><span class="glyphicon glyphicon-arrow-left"></span></a></h1><br><div class="row"><div class="col-md-2"></div><div class="col-md-8"><center><div id="carousel-example-generic"class="carousel slide"data-interval="false"><!--Wrapper for slides--><div class="carousel-inner"><div class="item active"><img src="img/june/page01.jpg"alt=""></div><div class="item"><img src="img/june/page02.jpg"alt=""></div><div class="item"><img src="img/june/page03.jpg"alt=""></div><div class="item"><img src="img/june/page04.jpg"alt=""></div><div class="item"><img src="img/june/page05.jpg"alt=""></div><div class="item"><img src="img/june/page06.jpg"alt=""></div><div class="item"><img src="img/june/page07.jpg"alt=""></div><div class="item"><img src="img/june/page08.jpg"alt=""></div><div class="item"><img src="img/june/page09.jpg"alt=""></div><div class="item"><img src="img/june/page10.jpg"alt=""></div><div class="item"><img src="img/june/page11.jpg"alt=""></div><div class="item"><img src="img/june/page12.jpg"alt=""></div><div class="item"><img src="img/june/page13.jpg"alt=""></div><div class="item"><img src="img/june/page14.jpg"alt=""></div><div class="item"><img src="img/june/page15.jpg"alt=""></div><div class="item"><img src="img/june/page16.jpg"alt=""></div><div class="item"><img src="img/june/page17.jpg"alt=""></div><div class="item"><img src="img/june/page18.jpg"alt=""></div><div class="item"><img src="img/june/page19.jpg"alt=""></div><div class="item"><img src="img/june/page20.jpg"alt=""></div><div class="item"><img src="img/june/page21.jpg"alt=""></div><div class="item"><img src="img/june/page22.jpg"alt=""></div></div><!--Controls--><a class="left carousel-control"href="#carousel-example-generic"data-slide="prev"><span class="icon-prev"></span></a><a class="right carousel-control"href="#carousel-example-generic"data-slide="next"><span class="icon-next"></span></a></div></div><div class="col-md-2"></div></center>');
	});
	$('.julyissue').click(function () {
	$('#viewbox').html('<h1><a href="/tribunemagazine"><span class="glyphicon glyphicon-arrow-left"></span></a></h1><br><div class="row"><div class="col-md-2"></div><div class="col-md-8"><center><div id="carousel-example-generic"class="carousel slide"data-interval="false"><!--Wrapper for slides--><div class="carousel-inner"><div class="item active"><img src="img/july/page01.jpg"alt=""></div><div class="item"><img src="img/july/page02.jpg"alt=""></div><div class="item"><img src="img/july/page03.jpg"alt=""></div><div class="item"><img src="img/july/page04.jpg"alt=""></div><div class="item"><img src="img/july/page05.jpg"alt=""></div><div class="item"><img src="img/july/page06.jpg"alt=""></div><div class="item"><img src="img/july/page07.jpg"alt=""></div><div class="item"><img src="img/july/page08.jpg"alt=""></div><div class="item"><img src="img/july/page09.jpg"alt=""></div><div class="item"><img src="img/july/page10.jpg"alt=""></div><div class="item"><img src="img/july/page11.jpg"alt=""></div><div class="item"><img src="img/july/page12.jpg"alt=""></div></div><!--Controls--><a class="left carousel-control"href="#carousel-example-generic"data-slide="prev"><span class="icon-prev"></span></a><a class="right carousel-control"href="#carousel-example-generic"data-slide="next"><span class="icon-next"></span></a></div></div><div class="col-md-2"></div></center>');
	});


		});